version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data # Uncomment this line to persist data
      - ./startup_queries/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # varibles for postgres image using the .env file
      - POSTGRES_PASSWORD=${DATABASE_API_PASSWORD}
      - POSTGRES_USER=${DATABASE_API_USER}
      - POSTGRES_DB=test
