version: '3'
services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mosquitto.passwd:/mosquitto/config/mosquitto.passwd"
      - "./opt/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "1884:1884"
