# Add this file to the your user home directory
# clangd/PlatformIO Project Configuration File

#If:
#  PathMatch: [.*hardware/esp8266.*, .*\.platformio.*]

CompileFlags:
  Add:
    [
      -mlong-calls,
      -isysroot=$HOME/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/,
    ]
  Remove:
    [
      -fno-tree-switch-conversion,
      -mtext-section-literals,
      -mlongcalls,
      -fstrict-volatile-bitfields,
    ]
Diagnostics:
  Suppress: "pp_including_mainfile_in_preamble"
